---
apiVersion: v1 
kind: Secret 
metadata:
  name: dov-secret 
  namespace: dovns 
  labels:
    app: dov 
type: Opaque 
data:
  INSTANCE_NAME: dGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHN0cmluZw==
  DB_PASSWORD: Y2hhbmdlaXQ=
