---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  env: dev
  dept: eng

namePrefix: dev-

namespace: devns

replicas:
- name: dov-deploy
  count: 1

    #images:
    #- name: chukmunnlee/dov-bear
    #  newTag: v6-alpha

secretGenerator:
- name: dov-secret
  behavior: create
  literals:
  - INSTANCE_NAME="this is from kustomize"

patches:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: dov-ing
  path: patch.yaml
