apiVersion: v1
items:
- apiVersion: v1
  data:
    INSTANCE_NAME: dGhpcyBpcyBmcm9tIGt1c3RvbWl6ZQ==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"INSTANCE_NAME":"dGhpcyBpcyBmcm9tIGt1c3RvbWl6ZQ=="},"kind":"Secret","metadata":{"annotations":{},"labels":{"dept":"eng","env":"dev"},"name":"dev-dov-secret-f77bd42c9h","namespace":"devns"},"type":"Opaque"}
    creationTimestamp: "2023-10-27T03:06:37Z"
    labels:
      dept: eng
      env: dev
    name: dev-dov-secret-f77bd42c9h
    namespace: devns
    resourceVersion: "624910"
    uid: a57d8bd8-8623-408b-879d-3cd83a4d5301
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"dov","dept":"eng","env":"dev","skaffold.dev/run-id":"d9396e3e-3f1f-4b54-8bb5-ba818ddd713e"},"name":"dev-dov-svc","namespace":"devns"},"spec":{"ports":[{"port":8080,"targetPort":"dov-port"}],"selector":{"app":"dov","dept":"eng","env":"dev"},"type":"ClusterIP"}}
    creationTimestamp: "2023-10-27T03:06:37Z"
    labels:
      app: dov
      dept: eng
      env: dev
      skaffold.dev/run-id: d9396e3e-3f1f-4b54-8bb5-ba818ddd713e
    name: dev-dov-svc
    namespace: devns
    resourceVersion: "625348"
    uid: c335987b-3b6a-4bdd-bad2-7654fb5c982c
  spec:
    clusterIP: 10.245.57.93
    clusterIPs:
    - 10.245.57.93
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: dov-port
    selector:
      app: dov
      dept: eng
      env: dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"dov","dept":"eng","env":"dev","skaffold.dev/run-id":"d9396e3e-3f1f-4b54-8bb5-ba818ddd713e"},"name":"dev-dov-deploy","namespace":"devns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"dov","dept":"eng","env":"dev"}},"template":{"metadata":{"labels":{"app":"dov","dept":"eng","env":"dev","skaffold.dev/run-id":"d9396e3e-3f1f-4b54-8bb5-ba818ddd713e"},"name":"dov-po"},"spec":{"containers":[{"env":[{"name":"INSTANCE_HASH","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"envFrom":[{"secretRef":{"name":"dev-dov-secret-f77bd42c9h"}}],"image":"chukmunnlee/dov-bear:v5","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":3000},"periodSeconds":30,"timeoutSeconds":3},"name":"dov-container","ports":[{"containerPort":3000,"name":"dov-port"}],"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
    creationTimestamp: "2023-10-27T03:06:37Z"
    generation: 3
    labels:
      app: dov
      dept: eng
      env: dev
      skaffold.dev/run-id: d9396e3e-3f1f-4b54-8bb5-ba818ddd713e
    name: dev-dov-deploy
    namespace: devns
    resourceVersion: "625393"
    uid: 4f0d7278-ea93-44ce-b185-a582656b1f9e
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: dov
        dept: eng
        env: dev
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: dov
          dept: eng
          env: dev
          skaffold.dev/run-id: d9396e3e-3f1f-4b54-8bb5-ba818ddd713e
        name: dov-po
      spec:
        containers:
        - env:
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          envFrom:
          - secretRef:
              name: dev-dov-secret-f77bd42c9h
          image: chukmunnlee/dov-bear:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          name: dov-container
          ports:
          - containerPort: 3000
            name: dov-port
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-10-27T03:06:38Z"
      lastUpdateTime: "2023-10-27T03:06:38Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-10-27T03:06:37Z"
      lastUpdateTime: "2023-10-27T03:08:18Z"
      message: ReplicaSet "dev-dov-deploy-7f9c96f958" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"dov","dept":"eng","env":"dev","name":"dov-hpa"},"name":"dev-dov-hpa","namespace":"devns"},"spec":{"maxReplicas":6,"metrics":[{"resource":{"name":"memory","target":{"averageUtilization":30,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"dev-dov-deploy"}}}
    creationTimestamp: "2023-10-27T03:06:37Z"
    labels:
      app: dov
      dept: eng
      env: dev
      name: dov-hpa
    name: dev-dov-hpa
    namespace: devns
    resourceVersion: "625461"
    uid: 86afa348-1561-4788-931a-97ccf987be79
  spec:
    maxReplicas: 6
    metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 30
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: dev-dov-deploy
  status:
    conditions:
    - lastTransitionTime: "2023-10-27T03:06:52Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2023-10-27T03:08:37Z"
      message: the HPA was able to successfully calculate a replica count from memory
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2023-10-27T03:07:07Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 31
          averageValue: "42049536"
        name: memory
      type: Resource
    currentReplicas: 1
    desiredReplicas: 1
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/limit-rps":"5"},"labels":{"app":"dov","dept":"eng","env":"dev","name":"dov-ing"},"name":"dev-dov-ing","namespace":"devns"},"spec":{"ingressClassName":"nginx","rules":[{"host":"abc-123.nip.io","http":{"paths":[{"backend":{"service":{"name":"dev-dov-svc","port":{"number":8080}}},"path":"/","pathType":"Prefix"}]}}]}}
      nginx.ingress.kubernetes.io/limit-rps: "5"
    creationTimestamp: "2023-10-27T03:06:37Z"
    generation: 1
    labels:
      app: dov
      dept: eng
      env: dev
      name: dov-ing
    name: dev-dov-ing
    namespace: devns
    resourceVersion: "625079"
    uid: 21d62e6c-043d-4c08-ba36-7676a8c97a65
  spec:
    ingressClassName: nginx
    rules:
    - host: abc-123.nip.io
      http:
        paths:
        - backend:
            service:
              name: dev-dov-svc
              port:
                number: 8080
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 146.190.195.35
kind: List
metadata: {}
