---
apiVersion: v1
kind: Service
metadata:
  name: dov-hsvc
  namespace: dovns
  labels:
    app: dov
spec:
  clusterIP: None
  selector: 
    app: sdov
    dept: seng
  ports:
  - port: 8080
    targetPort: sdov-port

---
apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: dov-sts
  namespace: dovns
  labels:
    app: dov 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sdov
      dept: seng
  serviceName: dov-hsvc
  template:
    metadata:
      name: dov-spo
      labels:
        app: sdov
        dept: seng
    spec: 
      containers:
      - name: dov-scontainer 
        image: chukmunnlee/dov-bear:v5 
        imagePullPolicy: IfNotPresent
        env: 
        - name: INSTANCE_HASH
          valueFrom: 
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: dov-secret
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - name: sdov-port 
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz 
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
