apiVersion: v1
data:
  INSTANCE_NAME: dGhpcyBpcyBmcm9tIGt1c3RvbWl6ZQ==
kind: Secret
metadata:
  labels:
    dept: eng
    env: dev
  name: dev-dov-secret-Fri27Oct2023-f77bd42c9h
  namespace: devns
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dov
    dept: eng
    env: dev
  name: dev-dov-svc-Fri27Oct2023
  namespace: devns
spec:
  ports:
    - port: 8080
      targetPort: dov-port
  selector:
    app: dov
    dept: eng
    env: dev
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dov
    dept: eng
    env: dev
  name: dev-dov-deploy-Fri27Oct2023
  namespace: devns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dov
      dept: eng
      env: dev
  template:
    metadata:
      labels:
        app: dov
        dept: eng
        env: dev
      name: dov-po
    spec:
      containers:
        - env:
            - name: INSTANCE_HASH
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - secretRef:
                name: dev-dov-secret-Fri27Oct2023-f77bd42c9h
          image: chukmunnlee/dov-bear:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 3
          name: dov-container
          ports:
            - containerPort: 3000
              name: dov-port
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: dov
    dept: eng
    env: dev
    name: dov-hpa
  name: dev-dov-hpa-Fri27Oct2023
  namespace: devns
spec:
  maxReplicas: 6
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 30
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-dov-deploy-Fri27Oct2023
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
  labels:
    app: dov
    dept: eng
    env: dev
    name: dov-ing
  name: dev-dov-ing-Fri27Oct2023
  namespace: devns
spec:
  ingressClassName: nginx
  rules:
    - host: abc-123.nip.io
      http:
        paths:
          - backend:
              service:
                name: dev-dov-svc-Fri27Oct2023
                port:
                  number: 8080
            path: /
            pathType: Prefix
